
#= = = = = = = = = = = = = = = =
#- - - - - - - - - - - - - - - -
#       PROJET MITIGATE +
#- - - - - - - - - - - - - - - -
#= = = = = = = = = = = = = = = =

#Code created by Paul Bostyn the 26/10/2023 under the behalf of the Mitigate+
#Project with the CGIAR 


#-_-_-_-__-_-_-_-_-_-_-_-_-_-_-_-_-_-_-
# I - Loading package and explanation ----
#-_-_-_-__-_-_-_-_-_-_-_-_-_-_-_-_-_-_-

"The aim of this script is to determine the profit or loss realised by the plantation
of forest according to different price level. And obtain the net present value / ton of
Carbon sequestred regarding specific level of tree cover and price used."

library(tidyverse)
library(FinancialMath)
library(dplyr)
library(readxl)
library(writexl)

#-_-_-_-__-_-_-_-_-_-_-_-_-_-_-_
# II - Data importation ----
#-_-_-_-__-_-_-_-_-_-_-_-_-_-_-_

Treecover <- c(7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22)#nothing to do  
#here the level of national tree cover in %

kmforesttoplant <- c(3260,9080,14920,20760,26590,32420,
                     38250,44080,49900,55810,61510,67360,73180,
                     78880,84860,90730)#nothing to do 
#here the quantity of km2 of forest needed in order to reach the tree cover
#linked (based on the tree cover of 2010)
valmeanseqcarbcookpatton <- mean(df2All$regrowthcookpatton, na.rm = T)
#-_-_-_-__-_-_-_-_-_-_-_-_-_-_-_
## a) Agricultural loss ----
#-_-_-_-__-_-_-_-_-_-_-_-_-_-_-_

"Below you have to insert data for Lossdata1,Lossdata2,Lossdata3"
#For example Lossdata1 com from the losses generated by the algorithm number one 1.
#So the excel Lossdata1 need to be fullfill by all the results obtain with algorithm 1.Same for
#the others algorithms.

Lossdata1 <-readxl::read_excel("Data/Data_Lossdata/Lossdata1.xlsx")
#insert the level of loss calculated from the algo 1 
#(the excel lossdata1 is coming from the excel"Atteinteobjectif avec seuil")

Lossdata2 <-readxl::read_excel("Data/Data_Lossdata/Lossdata2.xlsx")
#insert the level of loss calculated from the algo 2 - a (old name of this algorithm : 4-1)
#(the excel lossdata2 is coming from the excel"Atteinteobjectif avec seuil")

Lossdata3 <-readxl::read_excel("Data/Data_Lossdata/Lossdata3.xlsx")
for(i in 6:length(Lossdata3$Lossdata3)){
  Lossdata3$Lossdata3[i]<-NA
}#insert the level of loss calculated from the algo 2 - b (old name of algo : 4-2)
#(the excel lossdata3 is coming from the excel"Atteinteobjectif avec seuil")

dfall1 <- data.frame(Treecover,kmforesttoplant,Lossdata1,Lossdata2,Lossdata3)
remove(kmforesttoplant,Lossdata1,Lossdata2,Lossdata3)


#-_-_-_-__-_-_-_-_-_-_-_-_-_-_-_
## b) Wood Benefit ----
#-_-_-_-__-_-_-_-_-_-_-_-_-_-_-_

# Mean import value of Wood in Kenya (in $)
"Insert the level of this wood value"
meanimpwood <- 993 #Coming from the total mean (2010-2018) of the annual mean 
#price of a ton of wood imported (FAOSTAT-all wood products used) cf Excel "FAOSTAT_daaKenya_Woodproduction "
#in Dollars

# Mean export value of wood in Kenya (in $)
"Insert the level of this wood value"
meanexpwood <- 1200 #Coming from the total mean (2010-2018) of the annual mean 
#price of a ton of wood exported (FAOSTAT-all wood products used) cf Excel "FAOSTAT_daaKenya_Woodproduction "
#in Dollars

# Mondial price of wood 

"Import data of indexmundi"
dfhardsawnwood <-readxl::read_excel("Data/Data_Indexmundi/Hardsawnwood_indexmundi.xlsx")
#transforme la date
dfhardsawnwood %>%  mutate(mois=as.Date(mois, format = "%d.%m.%Y"))

dfhardlogs <-readxl::read_excel("Data/Data_Indexmundi/Hardslogs_indexmundi.xlsx")
#transforme la date
dfhardlogs %>%  mutate(mois=as.Date(mois, format = "%d.%m.%Y"))

dfsoftlogs <-readxl::read_excel("Data/Data_Indexmundi/Softlogs_indexmundi.xlsx")
#transforme la date
dfsoftlogs %>%  mutate(mois=as.Date(mois, format = "%d.%m.%Y"))

dfsoftsawnwood <-readxl::read_excel("Data/Data_Indexmundi/Softsawnwood_indexmundi.xlsx")
#transforme  la date
dfsoftsawnwood %>%  mutate(mois=as.Date(mois, format = "%d.%m.%Y"))

"Mean value of m cube of wood based on Indexmundi"
worldpricewoodmcube <- mean(c(mean(dfhardlogs$mcubeprice),mean(dfhardsawnwood$mcubeprice),mean(dfsoftlogs$mcubeprice),
                              mean(dfsoftsawnwood$mcubeprice)))

"Calcul the conversion factor for m cube to ton"
Import2010tonofwoodKenya <- 284181 #Coming from FAOSTAT see excel "FAOstat_daaKenya_Woodproduction" - Part Ana_1
Import2010mcubeofwoodKenya <- 72241 #Coming from FAOSTAT see excel "FAOstat_daaKenya_Woodproduction" - Part Ana_1
Export2010tonofwoodKenya <- 14610 #Coming from FAOSTAT see excel "FAOstat_daaKenya_Woodproduction" - Part Ana_1
Export2010mcubeofwoodKenya <- 17942 #Coming from FAOSTAT see excel "FAOstat_daaKenya_Woodproduction" - Part Ana_1
conversfactorwood <- mean(c((Import2010mcubeofwoodKenya/Import2010tonofwoodKenya),
                            (Export2010mcubeofwoodKenya/Export2010tonofwoodKenya)))

"Insert the conversion factor for m cube to ton if you have one precise"
#conversfactorwood <- 1

"Conversion of m cube price to ton price
giving the world wood price for a ton"
worldpricewoodton <-worldpricewoodmcube*conversfactorwood
sum(df2All$maxlnH2016,na.rm = T)
# production of ton of wood/km2
TreecoverofKenya <- round(((sum(df2All$Forestkm2, na.rm = T)/sum(df2All$maxlnH2016, na.rm = T))*100),2)
TreecoverofKenya <- 6.44 #Based from the Global forest Watch data of 2010 (as see over)
Kenyasuperficiekm2 <- 591958 #Total superficie Kenya based on the value given by the United Nations (from wikipedia) 
ProductionofwoodofKenya2010 <- 975245 #here insert value if you have one (in ton metric) (this
#value come from FAO STAT cf excel "FAOSTAT_daaKenya_Woodproduction")

#data on another year
forestkenyakm2 <- (TreecoverofKenya/100)*Kenyasuperficiekm2
prodctntonwoodbykm2kenya2010 <- ProductionofwoodofKenya2010/forestkenyakm2
prodctntonwoodbykm2kenya2010 <- round(prodctntonwoodbykm2kenya2010, digits = 0)

#Wood production in ton for each % tree cover reached on the reforested area
dfall1$woodprodctninton <- dfall1$kmforesttoplant*prodctntonwoodbykm2kenya2010

# Selling of wood producted at different price : 
dfall1$Sellingwoodimportprice <- dfall1$woodprodctninton*meanimpwood
dfall1$Sellingwoodworldprice <- dfall1$woodprodctninton*worldpricewoodton
dfall1$Sellingwoodexportprice <- dfall1$woodprodctninton*meanexpwood

# Add the benefit from the sell of wood

# Algorithm 1
dfall1$benef1importprice <- dfall1$Sellingwoodimportprice-dfall1$Lossdata1
dfall1$benef1worldprice <- dfall1$Sellingwoodworldprice-dfall1$Lossdata1
dfall1$benef1exportprice <- dfall1$Sellingwoodexportprice-dfall1$Lossdata1

#Algorithm 2
dfall1$benef2importprice <- dfall1$Sellingwoodimportprice-dfall1$Lossdata2
dfall1$benef2worldprice <- dfall1$Sellingwoodworldprice-dfall1$Lossdata2
dfall1$benef2exportprice <- dfall1$Sellingwoodexportprice-dfall1$Lossdata2

#Algorithm 3
dfall1$benef3importprice <- dfall1$Sellingwoodimportprice-dfall1$Lossdata3
dfall1$benef3worldprice <- dfall1$Sellingwoodworldprice-dfall1$Lossdata3
dfall1$benef3exportprice <- dfall1$Sellingwoodexportprice-dfall1$Lossdata3

#The real production of wood for all the Kenya with the
#initial amount of forest (6.44% tree cover) + the additional
#area of forest coming from the reforested area :
dfall1$WoodprodinallKenya <-dfall1$woodprodctninton+ProductionofwoodofKenya2010
#This column WoodprodinallKenya give the national production of wood in ton
#Based on the production of 2010, for all the Kenya, not only on the reforested
#area

remove(dfhardlogs,dfhardsawnwood,dfsoftlogs,dfsoftsawnwood)

#-_-_-_-__-_-_-_-_-_-_-_-_-_-_-_-_-_-_
## c) Carbon sequestration benefit ----
#-_-_-_-__-_-_-_-_-_-_-_-_-_-_-_-_-_-_

dfall1$carbonsequestbyyear <- valmeanseqcarbcookpatton*dfall1$kmforesttoplant*100
#Column carbonsequestbyyear give the mean ton of carbon sequestered each year in
#addition by the expension of forest (valmeanseqcarbcookpatton is based on the
#data from Susan Cook-Patton (2017) and GlobalForestwatch coming from the
#R_code1, it gives the mean value  (in ton) of carbon sequestred for 1 ha in Kenya for 1 year).
#So it needs to have lunch the part 5 in part V of the R_code1)
dfall1$CO2sequestbyyear <- dfall1$carbonsequestbyyear*3.67
#Column CO2sequestbyyear give the mean ton of CO2 (from the carbonsequestbyyear)
#3.67 is the ratio of transformation of carbon to CO2.

"Insert the value of ton of CO2 sequestred (in $) if you have one"
tonCO2reforesval <- 0
#Based on the "The social cost of carbon revisited" - Pyndick - 2019 
#Journal of Environmental Economics and Management --> this value of 80 is the social cost of carbon
#based on a period of 50 years, based on the hypothesis that the reforestation will stay for a period longer than 50 years

#Another value is 14 $/ ton de CO2 coming from the average price of the carbon credit for reforestation
#project : https://www.abatable.com/blog/carbon-credits-pricing


dfall1$benefCO2SCC <- dfall1$CO2sequestbyyear*tonCO2reforesval
#The Column benefCO2SCC give in dollars the total value (linked to a level
#of tree cover) of the annual social cost of carbon avoided by the reforestation (based on 50 years period see above).



#Evolution of wood demand 
#For the period of 2010-2018 (according to FAO stat):
Meanimportwoodtonbyyear <- 287605 #FAOdata
Meanexportwoodtonbyyear <- 23791 #FAOdata
Meanproducwoodtonbyyear <- 1116868 #FAOdata
Meanpopul <- 45794519 #Worldbank data
#The mean annual demand of wood by people (for period 2010 to 2018 from FAOstat)
demandbypeople <- (Meanimportwoodtonbyyear-Meanexportwoodtonbyyear+
                     Meanproducwoodtonbyyear)/Meanpopul
#The evolution of this demand regarding the evolution of population
#According to : https://population.un.org/wpp/Download/Standard/Population/    
"Import the data called : evolpopdemand"
evolpopdemand <- read_excel("Data/Data_evolpopulation/evolpopdemand.xlsx")

#Add the evolution of wood demand 
evolpopdemand$wooddemandinton <- evolpopdemand$poptotkenya*demandbypeople

#-_-_-_-_-__-_-_-_-_-_-__-_-_-_
## d) Precipitation benefit ----
#-__-_-_-_-_-_-_-_-_-_-__-_-_-

#Pour le code ci-dessous on calcule combien une hausse de x % de la tree cover
#génère en hausse de précipitation (à partir des coefs "coefregpreci2" & "coefregpreci1").
#Et ensuite, combien cette hausse de la précipitation vaut en $.


"Get the value of the précipitation based on the global agricultural value"
#based on the Regpreci1 & Regpreci2 from the R_code1
#We have the increase of precipitation in one pixel for an increase in 1% of 
#tree cover give by the ' coefregpreci1 '  and same for the coefregpreci2.


#IF we don't gonna use the benefit from precipitation in the
#calcul of the mean net present value below you can launch the 2 lines below : 
coefregpreci2 <- 0
coefregpreci1 <- 0

#Then you can launch the lines below
benef1alg1 <- c(1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1)
benef2alg1 <- c(1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1)
Benefprecip <- data.frame(Treecover,benef1alg1,benef2alg1)
"Insert how much one mm of precipitation represent in cubic meter for one pixel :"
Manycubicmeter <- mean(df2All$maxlnH2016,na.rm=T)*1000000*0.001
#For more Explanation see Word "Valorisation relation forêt-précipitation"
#Convert 1mm of precip on a mean area of 84.808km² =~= 84 805,681 cubic meter of water
"Insert the % of green water on all the precipitation"
prcentgreenwater <- 0.65
"Insert the price choosen of in the article of P.D'Odorico - 2020 for one cubic meter"
priceofonecubicmeterwater <- 0.099 #price in dollars
#So 1 mm of precipitation is equal to for one pixel to valueof1moremmofprecip:
valueof1moremmofprecip <- priceofonecubicmeterwater*Manycubicmeter*prcentgreenwater
for(i in 1:length(Benefprecip$Treecover)){
  Benefprecip$benef1alg1[i] <- (Benefprecip$Treecover[i]-TreecoverofKenya)*coefregpreci2*12*valueof1moremmofprecip*6931
}#Simple Regression coefficient used here before

for(i in 1:length(Benefprecip$Treecover)){
  Benefprecip$benef2alg1[i] <- ((Benefprecip$Treecover[i]-TreecoverofKenya)*coefregpreci1)*12*valueof1moremmofprecip*6931
}#More complexe coefficient used here before
#The value of 0.25 is coming from the paper "The global value of water in agriculture" (P.D'Odorico et al. 2020)
#The 6931 is the number of pixel in Kenya
#We multiplied by 12 to get the annual increase of precipitation

#the cols benef1alg1 & benef2alg1 give the benefice in $ include in the increase of precipitation
#due to the reforestation for the Kenya for 1 year
dfall1$benef1preci <- Benefprecip$benef1alg1
dfall1$benef2preci <- Benefprecip$benef2alg1

#-_-_-_-__-_-_-_-_-_-_-_-_-_-_-_
## e) Cost of planting ----
#-_-_-_-__-_-_-_-_-_-_-_-_-_-_-_

#According to "Direct seeding reduces the costs of tree
#planting for forest and savanna restoration" - P. P. Raupp et al. 2020
#The differents prices for planting are ($/ha) : 
laborcostforplanting<-72.52
costforcontrolpredationseed<-16.79
costforavoidexoticgrass<-75.06 #All of these costs are presented 
#in the article page 3
for(i in 1:length(dfall1$Treecover)){
  dfall1$laborcost[i] <- dfall1$kmforesttoplant[i]*100*laborcostforplanting
}
for(i in 1:length(dfall1$Treecover)){
  dfall1$predationcontrolcost[i] <- dfall1$kmforesttoplant[i]*100*costforcontrolpredationseed
}
for(i in 1:length(dfall1$Treecover)){
  dfall1$exoticgrasscost[i] <- dfall1$kmforesttoplant[i]*100*costforavoidexoticgrass
}
#Give the total cost of tree planting
for(i in 1:length(dfall1$Treecover)){
  dfall1$totalcosttreeplanting[i] <- (dfall1$exoticgrasscost[i]+dfall1$predationcontrolcost[i]+
                                        dfall1$laborcost[i])
}


# -- In order to have xls of data 
dfventbois <- subset(dfall1[c("Treecover","Sellingwoodimportprice")], )
write_xlsx(dfventbois,"Data/dfventbois.xlsx")
dfwatergain <- subset(dfall1[c("Treecover","benef2preci")], )
write_xlsx(dfwatergain,"Data/dfwatergain.xlsx")
dfCO2gain <- subset(dfall1[c("Treecover","benefCO2SCC")], )
write_xlsx(dfCO2gain,"Data/dfCO2gain.xlsx")
remove(dfventbois,dfwatergain,dfCO2gain,Benefprecip)
dfcosttreeplant <- subset(dfall1[c("Treecover","totalcosttreeplanting")], )
remove(dfcosttreeplant)


#-_-_-_-__-_-_-_-__-_-_-_-_-_-_-_-_-_-_
# III - Analysis of the data ----
#-_-_-_-_-_-_-_-_-__-_-_-_-_-_-_-_-_-_-

### -- Launching starting point ----

#La boucle ci-dessous comprise entre  "-(-["   et  "]-)-"
#va être répéter pour l'ensemble des nombres compris entre numberstarting et
#numberending et les NPV obtenus vont être rentrées dans "dfvectorNPV"
#Si l'on veut une valeur précise pour seulement 1 seul niveau de tree cover
#Il suffit de mettre par exemple pour 7% de tree cover, 7 pour numberstarting
#et 7 pour numberending
numberstarting <-7#Correspond au % de tree cover que l'on souhaite sur le Kenya et étant
#le plus faible niveau de Tree cover (en%) que l'on souhaite avoir et obtenir sa NPV
numberending <-11#Pareil que pour le numberstarting mais pour le niveau max en
#sachant que le niveau max pour le Kenya d'après les algorithmes (avec les conditions
#que l'on a défini) est 22%. 
dfstockage <- read_excel("Data/DfstockageNPV.xlsx")
dfstockage2 <- read_excel("Data/DfstockageMeanNPVpertoncarbon.xlsx")
"If you use the algorithm 3 of ecological continuum that repeat until reach
the objectiv you can't put numberending over 11 include."
"Make sure you removed the file 'dfvectorNPV' in your R data "

#Inside the for loop the user need to precise the conditions : 

# -(-[
for(w in numberstarting:numberending){
  # --- Fixe the requirement for the analysis : 
  "Insert the level you want of tree cover (rounded to the nearest whole number)" 
  levelobj <- w
  ifelse(levelobj>22,"ERROR in level of tree cover indicated (max 22)","Good")
  ifelse(levelobj>22,
         stop(),"Good")
  "Insert the algorithm you want (1,2 or 3 only)"#Just reminder : Algo1 here = Algo1, Algo 2 = Algo 2 part a, Algo 3 = Algo 2 part b
  algoobj <- 3
  "Insert the level price you want (Only:1-Import,2-world,3-export)"
  levelpricobj <- 1
  "Insert the number of years estimated for the growth of the forest"
  growthfor <- 15
  "Insert the number of years of the time project (see Anx2) "
  timeproj <- 30 #The time of the project can't go over 2080 so 2080 - 2022 = 58 ; 59 is the max value you can insert (because 2080 is include)
  maxtimeproj <- 59
  "Insert the discounting rate in %"
  discrate <- 4.5
  #4.5% selon : https://annforsci.biomedcentral.com/articles/10.1007/s13595-017-0683-5
  # 7% selon : https://www.sciencedirect.com/science/article/abs/pii/S1104689916300988
  #entre 5% et 6,5% selon : https://ir.canterbury.ac.nz/bitstream/handle/10092/102429/Discount%20rate%20survey%202017.pdf?sequence=2
  
  "Insert which value you want for the value SQ78 (1 for NPV, 2 for sum)"
  valsq <- 1
  "Insert the value that allow to consider that the supply fullfill
the demand (see Anx3)"
  valsupldmd <- 100
  "Insert 1 if you want to add the value of carbon sequestration and 0 if not"
  valcarbcond <- 1
  "Insert 1 if you want to add the value of the precipitation and 0 if not"
  valprecipation <- 0
  "Which method for the precipitation value : 1 - the precipitation value is based
on the the easiest regression and the global value of water in agriculture 
(coming from P. D'odorico - 2020)
2 - the precipitation value is based on a more complexe regression with dummies and
 the global value of water in agriculture (the number 2 is recommanded) (only 1 or 2)"
  valmethodprecipitation <- 2
  ifelse(valmethodprecipitation == 1, datacol1 <- dfall1$benef1preci,
         datacol1 <- dfall1$benef2preci)
  "Insert which type of wood price is applied during the period
of the fullfillment of the demand by the supply (2-World price
or 3-Export price)"
  valuehere <- 3
  "Do we consider that the period of growing of the forest is also a period 
to sequester carbon (1 if yes and 0 if no, but the best here is to say yes)."
  varcarbduringgrowth <- 1
  "Insert if you want to take into account the labor cost showed by P. P. Raupp et al. 2020
(see above) 1 if yes 0 if no"
  reqlaborcost <- 1
  "Insert if you want to take into account the cost to avoid predation of the seed by Raupp et al
1 if yes and 0 if no"
  reqpredacost <- 1
  "Insert if you want to take into account the cost of herbicide to avoid exotic grass given
by Raupp et al. 2020   - 1 if yes and 0 if no"
  reqexotcost <- 1
  #Information : La Net Present value est calculée à partir du coût de plantation comme investissement initial
  
  
  #Conditions
  ifelse(levelobj >= 12 & algoobj == 3,
         "The Algorithm n°3 can't have a tree cover superior to 12%
       of tree cover, you can change your insertion
       and launch again","")
  ifelse(levelobj >= 12 & algoobj == 3,stop(),"")
  
  #-- PART 1 - Without market phenomenom
  
  #Then launch the next lines to know the result(line by line) : 
  dfresearch <- dfall1[ , grepl( algoobj , names( dfall1 ) ) ] #select col with algoobj
  dfresearch <- dfresearch[,-1]#remove the first column 
  value1 <- dfresearch[levelobj-6,levelpricobj]
  #more info on this code see Anx1
  
  ifelse(valcarbcond == 1,value1<-value1+dfall1$benefCO2SCC[levelobj-6],value1)
  ifelse(valprecipation == 1, value1 <- value1+datacol1[levelobj-6],value1)
  "The benefit or loss generated each year with these conditions is ($) :"
  value1
  
  "The total benefit or loss of the project (taking into account the loss during
the growth of the forest) is ($) :"
  dfresearch2 <- dfall1[ , grepl(algoobj , names( dfall1 ) ) ]
  value2 <- dfresearch2[levelobj-6,1]
  value3 <- value1*(timeproj-growthfor)-(growthfor*value2)
  value3#Here value 3 give the total benefit or total loss for the entire time of the project
  
  "To have the representation of the benefit and/or loss :"
  dfpres <- data.frame(time = c(1:timeproj),
                       benef = runif(timeproj))
  for(i in 1:growthfor){dfpres$benef[i] <- (value2*(-1))}
  for(i in (growthfor+1):timeproj){dfpres$benef[i] <- value1}
  plot(dfpres$time,dfpres$benef,xlab = "Year",
       ylab = "Benefit/Loss in $",main="Evolution of benefit or loss by time")
  remove(dfpres)
  
  #-- PART 2 - With Market Phenomenon
  "-----------------------------------------------------------------------------------
---------------------MARKET PHENOMENON OF THE PRICE --------------------------------"
  
  "Theses results before don't take into account the market phenomenon of supply and
demand on the price of wood. If we consider that the price of wood will change
with the level of supply, we can have theses results :"
  
  dfsupplydemand <- evolpopdemand[c("year","wooddemandinton")]
  dfsupplydemand$supply <- dfall1[(levelobj-6),"woodprodctninton"]
  dfsupplydemand$supply2 <- dfall1[(levelobj-6),"WoodprodinallKenya"]
  dfsupplydemand <- head(dfsupplydemand, - (maxtimeproj - timeproj)) #Remove the line for the year in surplus
  Dfbenefmarket <- dfsupplydemand
  dfsupplydemand$prcentsupplydmand <- (dfsupplydemand$supply2/dfsupplydemand$wooddemandinton)*100
  dfsupplydemand<-dfsupplydemand %>%  filter(!row_number() %in% c(1:growthfor))
  
  #Explanation of the code over : Il dit que pour toutes les années du projet 
  #il va produire  au niveau national le niveau de "WoodprodinallKenya" indiqué, 
  #par contre il va produire le niveau woodprodctninton sur les zones reforestées.
  #Ensuite il calcule le %
  #de réponse de la demande par ce niveau de production de bois (à l'échelle nationale),
  #ensuite il supprime les 
  #premières lignes correspondant au nombre d'année où la forêt va se développer.
  
  #The column supply give the wood production in ton for a specific tree cover
  
  #Obtain the benef from the sale of wood in a df for each year in the dfsupplydemand
  #where there are only years when we can sell the wood (after the period of growth for the forest)
  if(levelpricobj == 1){valwood <-meanimpwood}#Allow to keep the requirement of the wood of price apply
  if(levelpricobj == 2){valwood <-worldpricewoodton}
  if(levelpricobj == 3){valwood <-meanexpwood}
  valwoodintegratmarket <- ifelse(valuehere == 2,worldpricewoodton,meanexpwood)
  dfsupplydemand$newbenefofwood <- dfsupplydemand$year
  for(i in 1:length(dfsupplydemand$year)){
    dfsupplydemand$newbenefofwood[i] <- ifelse(dfsupplydemand$prcentsupplydmand[i] > 100,
                                               dfsupplydemand$wooddemandinton[i]*valwood+
                                                 (dfsupplydemand$supply[i]-dfsupplydemand$wooddemandinton[i])*valwoodintegratmarket,
                                               dfsupplydemand$supply[i]*valwood)
  }
  
  #Obtain a df with the wood benefits for all the time of the project
  #In Dfbenefmarket there is all the period of the project even if there are no benefits.
  #And all time regarding the requirement fixed earlier 
  Dfbenefmarket <- Dfbenefmarket[ , !(names(Dfbenefmarket) %in% c("wooddemandinton","supply","supply2"))]
  for(i in 1:growthfor){
    Dfbenefmarket$Woodbenef[i] <- 0
  }
  for(i in (growthfor+1):length(Dfbenefmarket$year)){
    Dfbenefmarket$Woodbenef[i] <- ifelse(dfsupplydemand$year[i-growthfor] == Dfbenefmarket$year[i],
                                         dfsupplydemand$newbenefofwood[i-growthfor],0)
  }
  
  #Add the agricultural losses for the requirements fixed. 
  growth_rate=0.056 #Calculated to be equal to 120% in 2050 according to the simulations from EMF33 R5B0 median values of all models in 2050
  Dfnecessarycost <- dfall1[ , grepl( algoobj , names( dfall1 ) ) ]#select the column name containing the
  #value of algoobj in their name 
  valuecostmarket <- Dfnecessarycost[levelobj-6,1]#see Appendice
  for(i in 1:length(Dfbenefmarket$year)){
    Dfbenefmarket$Cost[i] <- valuecostmarket*(1+i*growth_rate)
  }
  
  #Add CO2 benefit for each year where it's possible to sequester.
  valueCO2benefmarket <- dfall1$benefCO2SCC[levelobj-6]
  for(i in 1:growthfor){Dfbenefmarket$CO2benef[i]<-ifelse(varcarbduringgrowth ==1,
                                                          valueCO2benefmarket,0)}
  for(i in (growthfor+1):length(Dfbenefmarket$year)){
    Dfbenefmarket$CO2benef[i]<-valueCO2benefmarket
  }
  #Regarding the facts that 1) Forests sequester carbon during the growing period
  #2) The rate that we used to compute the level of carbon sequestered from CookPatton
  #is based on a natural regrowth of the forest so it's a rate that take into account the period of growth.
  
  
  #Add Water benefit
  Dfwatermarketpheno <- dfall1[ , grepl("preci", names(dfall1))]#select colum with preci
  valuewaterbenefmarket <- Dfwatermarketpheno[levelobj-6,valmethodprecipitation]
  for(i in 1:growthfor){Dfbenefmarket$Waterbenef[i]<-0}
  for(i in (growthfor+1):length(Dfbenefmarket$year)){
    Dfbenefmarket$Waterbenef[i]<- valuewaterbenefmarket
  }
  remove(Dfnecessarycost,valuewaterbenefmarket,valueCO2benefmarket,
         Dfwatermarketpheno)
  
  
  #Add Tree planting cost
  # -- Labor cost
  dftreeplantingcost <- dfall1[ , grepl("cost", names(dfall1))]
  valuecostlabor <- dftreeplantingcost[levelobj-6,1]
  for(i in 1:1){ifelse(reqlaborcost == 1,
                       Dfbenefmarket$laborcost[i]<-valuecostlabor,
                       Dfbenefmarket$laborcost[i]<-0)}
  for(i in 2:length(Dfbenefmarket$year)){Dfbenefmarket$laborcost[i]<-0}
  remove(dftreeplantingcost,valuecostlabor)
  # -- Predation control cost
  dftreeplantingcost <- dfall1[ , grepl("cost", names(dfall1))]
  valuecostpreda <- dftreeplantingcost[levelobj-6,2]
  for(i in 1:1){ifelse(reqpredacost == 1,
                       Dfbenefmarket$predacost[i]<-valuecostpreda,
                       Dfbenefmarket$predacost[i]<-0)}
  for(i in 2:length(Dfbenefmarket$year)){Dfbenefmarket$predacost[i]<-0}
  remove(dftreeplantingcost,valuecostpreda)
  # -- Grass control cost
  dftreeplantingcost <- dfall1[ , grepl("cost", names(dfall1))]
  valuecostgrass <- dftreeplantingcost[levelobj-6,3]
  for(i in 1:1){ifelse(reqexotcost == 1,
                       Dfbenefmarket$grasscost[i]<-valuecostgrass,
                       Dfbenefmarket$grasscost[i]<-0)}
  for(i in 2:length(Dfbenefmarket$year)){Dfbenefmarket$grasscost[i]<-0}
  remove(dftreeplantingcost,valuecostgrass)
  
  #Group all cost together :
  for(i in 1:length(Dfbenefmarket$year)){
    Dfbenefmarket$costplanting[i]<-(Dfbenefmarket$laborcost[i]+Dfbenefmarket$predacost[i]+
                                      Dfbenefmarket$grasscost[i])
  }
  
  
  #Got the total benefit or loss, taking into account each benefit or loss from water, carbon, wood, agricultural losses
  for(i in 1:length(Dfbenefmarket$year)){
    Dfbenefmarket$totalbeneforlosswithmarket[i] <- (Dfbenefmarket$Woodbenef[i]-Dfbenefmarket$Cost[i]+
                                                      Dfbenefmarket$CO2benef[i]+Dfbenefmarket$Waterbenef[i]
                                                    -Dfbenefmarket$costplanting[i])
  }
  for(i in 1:length(Dfbenefmarket$year)){
    Dfbenefmarket$totbenefwithoutcarbon[i] <- (Dfbenefmarket$Woodbenef[i]-Dfbenefmarket$Cost[i]+Dfbenefmarket$Waterbenef[i]
                                               -Dfbenefmarket$costplanting[i])
  }
  for(i in 1:length(Dfbenefmarket$year)){
    Dfbenefmarket$totbenefwithoutwater[i] <- (Dfbenefmarket$Woodbenef[i]-Dfbenefmarket$Cost[i]+Dfbenefmarket$CO2benef[i]
                                              -Dfbenefmarket$costplanting[i])
  }
  for(i in 1:length(Dfbenefmarket$year)){
    Dfbenefmarket$totbenefwithoutwaterandcarbon[i] <- (Dfbenefmarket$Woodbenef[i]-Dfbenefmarket$Cost[i]
                                                       -Dfbenefmarket$costplanting[i])
  }
  "If you look at the Dfbenefmarket you will see each year the benefit or the loss regarding the
condition you fixed earlier with a situation that take into account the mecanism of demand and supply
that incluence the price of wood. But don't forgot that the benefit of CO2 is just for one year.
I put the benefit from carbon sequestred just after the time of growing for the forest but it can be placed
at another year."
  "
   "
  "Here for all the time of the project the benefit or the loss is assessed to be ($) (
regarding the requirement fixed earlier) :"
  if(valcarbcond == 1 & valprecipation == 1) {sum(Dfbenefmarket$totalbeneforlosswithmarket, na.rm = T)}
  if(valcarbcond == 0 & valprecipation == 1) {sum(Dfbenefmarket$totbenefwithoutcarbon, na.rm = T)}
  if(valcarbcond == 1 & valprecipation == 0) {sum(Dfbenefmarket$totbenefwithoutwater, na.rm = T)}
  if(valcarbcond == 0 & valprecipation == 0) {sum(Dfbenefmarket$totbenefwithoutwaterandcarbon, na.rm = T)}
  
  if(valcarbcond == 1 & valprecipation == 1) {Totbenef <- data.frame(Dfbenefmarket$year,Dfbenefmarket$totalbeneforlosswithmarket)}
  if(valcarbcond == 0 & valprecipation == 1) {Totbenef <- data.frame(Dfbenefmarket$year,Dfbenefmarket$totbenefwithoutcarbon)}
  if(valcarbcond == 1 & valprecipation == 0) {Totbenef <- data.frame(Dfbenefmarket$year,Dfbenefmarket$totbenefwithoutwater)}
  if(valcarbcond == 0 & valprecipation == 0) {Totbenef <- data.frame(Dfbenefmarket$year,Dfbenefmarket$totbenefwithoutwaterandcarbon)}
  
  #Valeur d'investissement initiale :
  colnames(Totbenef)[1] = "year" #rename col
  colnames(Totbenef)[2] = "totalbeneforloss"
  cf0 <- Dfbenefmarket$costplanting[1]
  valattente <- Totbenef$totalbeneforloss[1]
  Totbenef$totalbeneforloss[1]<- Totbenef$totalbeneforloss[1]+cf0
  Dfbenefmarket3 <- Totbenef
  cf <-  Dfbenefmarket3$totalbeneforloss
  remove(Dfbenefmarket3)
  "If we use a discounting rate on the total benefit over time (here the initial investment is
the cost of planting and the cashflows are the annual difference between benefits and losses
during all the time of the project) the Net Present Value is :"
  NPV(cf0, cf, times=c(1:timeproj), i=(discrate/100))
  NPVproject <- NPV(cf0, cf, times=c(1:timeproj), i=(discrate/100))# -> source : https://www.codingprof.com/how-to-calculate-the-net-present-value-npv-in-r-examples/?utm_content=cmp-true
  #Rappel : Net Present Value = -Investment + Cash flow of the year 1 x ((1+i)^-1) + Cash flow of the year 2x((1+i)^-2)
  
  #checking the NPV 
  discrate2<-0
  NPV(cf0, cf, times=c(1:timeproj), i=(discrate2/100))
  Totbenef$totalbeneforloss[1]<-valattente #remettre la valeur initiale
  sum(Totbenef$totalbeneforloss) #if NPV and sum don't give the same result there is an error
  print("Checking, it should give 0 :")
  print((NPV(cf0, cf, times=c(1:timeproj), i=(discrate2/100))-sum(Totbenef$totalbeneforloss)))
  
  "Without discounting rate, in this part (market phenomenon with demand and supply),
the total benef or loss for all the time of the project is : "
  sum(Totbenef$totalbeneforloss)
  
  #Compute the cost or benefit for each ton of carbone sequester - SQ78
  Dfcarbonseqstr <- dfall1[ , grepl("sequest", names(dfall1))]#select colum with preci
  valuecarbonsqstrannuelle <- Dfcarbonseqstr[levelobj-6,1]#see Appendice
  valuecarbonsqstrtotal <- valuecarbonsqstrannuelle*(timeproj)
  ifelse(valsq == 1,
         valsq2 <- NPVproject,
         valsq2 <- sum(Totbenef$totalbeneforloss))
  Valuebeneficeorlosspercarbonsequestr <- valsq2/valuecarbonsqstrtotal#en tonne 
  
  "The benef or loss for each ton of carbon sequester for all the time of the project is (in $)
by taking : the NPV/quantity of carbon in ton sequester (it's in average in ton of carbon per year):"
  Valuebeneficeorlosspercarbonsequestr
  
  "The benef or loss for each hectare for all the time of the project (in $/ha) by computing 
NPV/quantity of hectare reforested:"
  valkmoftheproject <- dfall1[levelobj-6,2]
  valsq2/(valkmoftheproject*100)
  
  #Stock the value in a df 
  dfstockage <- rbind(dfstockage,NPVproject)
  dfstockage2 <- rbind(dfstockage2,Valuebeneficeorlosspercarbonsequestr)
  
  #Cleaning for the calculation of the NPV 
  remove(dfresearch,dfresearch2,valuehere,discrate,discrate2,
         Totbenef,Dfcarbonseqstr)
  
  
}
# ]-)-
dfstockage <- dfstockage[-c(1,2),]
dfstockage$Treecover<-c(numberstarting:numberending)
dfstockage2 <- dfstockage2[-c(1,2),]
dfstockage2$Treecover<-c(numberstarting:numberending)
dfstockage <- full_join(dfstockage, dfstockage2, by = "Treecover")
remove(dfstockage2)

### -- Launching ending point ----

#dfvectorNPV contient les NPV pour les différentes tree cover associées 
#en fonction des conditions que l'on a posé 
write_xlsx(dfstockage,"Data/dfvectorNPV.xlsx")
#Necessary to remove the file dfvectorNPV before creating the new xlsx
write_xlsx(dfsupplydemand,"Data/dfsupplydemad.xlsx")
write_xlsx(dfall1,"Data/dfall1te.xlsx")


# IV - Cleaning/Nettoyage ----
remove(numberending,numberstarting,dfvectorNPV,treecoverhere,dfstockage)
remove(dfsoftlogs,dfsoftsawnwood,dfhardlogs,dfhardsawnwood)
remove(dfsoftlogs,dfsoftsawnwood,dfhardlogs,dfhardsawnwood,worldpricewoodmcube,
       worldpricewoodton,Import2010mcubeofwoodKenya,Import2010tonofwoodKenya,
       Export2010mcubeofwoodKenya,Export2010tonofwoodKenya,
       dfresearch,value,dfresearch2,value2,value3,meanexpwood,meanimpwood,
       levelobj,levelpricobj,algoobj,growthfor,timeproj,Kenyasuperficiekm2,
       discrate,discrate2,ProductionofwoodofKenya2010,ProductionofwoodofKenya2010,benef,dfpres,
       dfall1,conversfactorwood,forestkenyakm2,TreecoverofKenya,value1,value3_a,
       value2_a,value1_a,dfresearch3,dfresearch4,VPN,dfbeneflossdisc,dfsupplydemand,
       evolpopdemand,Valdef1,Valdef2,prodctntonwoodbykm2kenya2010,forestkenyakm2,
       numbryears,valif3,valuebenefloss1,valuebenefloss2,valuehere,VAN,Meanpopul,
       Meanproducwoodtonbyyear,Meanimportwoodtonbyyear,Meanexportwoodtonbyyear,
       demandbypeople,Benefprecip,valuecostmarket,valwoodintegratmarket)
remove(Dfbenefmarket,Dfbenefmarket2,Dfbenefmarket3,Totbenef)
remove(dfstockage2)


## -- Appendices ----

#Anx1 -> here the objectif is to select the value with the condition specified
#by the user. So the Grep function allow to select data only concern by the algoobj
#For instance, if specified 1 -> all colum with "1" in there name will be selected
# so we don't have to add new colum with 1 in their name if they didn't concern
#algorithm 1. 
#Here value1 give the benefit or the loss generated by : the production of wood - the agricultural losses

#Anx2 -> For instance if the objectif is to see at the horizon of 2050 
#and if we based on 2020 as starting date, the time of project will be 30 
#After 2050 there is no more population forecast made by World Bank so 
#We continue the population forecast until 2080 with method defined in 
#Word " Valorisation du bois".

#Anx3 -> We will calculate the % of : Supply / Demand  , so if this %
#is > to valsupldmd we can consider that the supply fullfill the demand
#so we can consider that the price of woo will be the international price
#Don't forget that we made a forecast concerning the population to reach 2080
#this forecast is explained in the doc Word " Valorisation du bois".

#valuecostmarket -> give the value of the agricultural loss giving the conditions established before
#for the situation where we want to take into account the market phenomenom of the interraction between
#SUpply and demand.
#Waterbenef -> give the value of the benef generated with the increase of precipitation in a situation
#where we take into account the market phenomenom

#totalbeneforlosswithmarket  it gives the total value of the benefit or the loss for all the time of the project
#for example if it gives 100 it means during all the time of the project, and taking into account the market
#phenomenom of demand and supply, the benefit of the project at the end is 100.



